name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install --no-interaction
    
    - name: Format code
      if: github.event_name == 'pull_request'
      run: |
        poetry run black .
        poetry run isort .
    
    - name: Commit formatting changes
      if: github.event_name == 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-format code with Black and isort"
        file_pattern: "*.py"
    
    - name: Run linting check
      run: |
        poetry run black --check .
        poetry run isort --check .
    
    - name: Run type checking
      run: poetry run mypy .
    
    - name: Run tests
      run: poetry run pytest --cov=luthien_code_control